solver: board.h board.c logic.h logic.c solver.c
	clang -Wall -g -O0 -o solver board.c logic.c solver.c

debugger: board.h board.c logic.h logic.c debug.c
	clang -Wall -g -O0 -o debugger board.c logic.c debug.c
